import {describe,it,expect} from 'vitest';
import {HEADERS,validateBase,buildView,defaultFilters,addDays,DIMENSIONS,type Dimension,type Filters} from '../src/lib/domain';
import {executiveRanking,weightedRetentionDays,formatRankingPercent,formatWeightedDays} from '../src/lib/executive-ranking';
const cut='2026-09-30';
const row=(id:string,days:number,amount:number,company='A',uf='SP',client='Cliente A',billing:string|null=null)=>[company,id,addDays(cut,-days),'Eletiva',client,uf,'Hospital '+uf,uf,'Médico',null,'Representante '+uf,billing,null,amount];
const ds=(rows:unknown[][])=>validateBase([...HEADERS],rows,cut,'exemplo.xlsx');
const f=(extra:Partial<Filters>={})=>({...defaultFilters(),...extra});
const view=(d:ReturnType<typeof ds>,filters=f(),dim:Dimension='customer')=>{const v=buildView(d,filters);return {v,r:executiveRanking(v.surgeries,dim,v.period.end,v.summary.pending)};};
describe('Ranking executivo: apenas percentuais e média financeira da apresentação',()=>{
 it('exemplo oficial: média ponderada de 138 dias; KPI simples permanece em 100',()=>{const {v,r}=view(ds([row('1',30,10000),row('2',90,30000),row('3',180,60000)]));expect(r[0].weightedMean).toBe(138);expect(r[0].share).toBe(1);expect(r[0].count).toBe(3);expect(v.summary.mean).toBe(100);expect(v.rankings.customer[0].mean).toBe(100);});
 it('25% do universo filtrado com duas casas e média com uma',()=>{const {r}=view(ds([row('1',30,2500000,'A','SP','Cliente A'),row('2',90,7500000,'A','SP','Cliente B')]));expect(r.find(x=>x.name==='Cliente A')!.share).toBe(.25);expect(formatRankingPercent(.25)).toBe('25,00%');expect(formatWeightedDays(138)).toBe('138,0');});
 it('denominador anterior ao Top N: todas categorias somam 100%, Top 5 não',()=>{const {v,r}=view(ds(Array.from({length:12},(_,i)=>row(String(i),30+i,100*(i+1),'A','SP',`Cliente ${i}`))));expect(r.reduce((a,r)=>a+r.share,0)).toBeCloseTo(1,12);const top=r.slice(0,5);expect(top.reduce((a,r)=>a+r.share,0)).toBeLessThan(1);expect(top[0].share).toBe(top[0].cents/v.summary.pending);expect(r.map(x=>x.cents)).toEqual([...r.map(x=>x.cents)].sort((a,b)=>b-a));});
 it('faturamento parcial usa somente saldo pendente, repetição não duplica cirurgias',()=>{const {v,r}=view(ds([row('1',30,10000),row('1',30,90000,'A','SP','Cliente A','2026-09-01'),row('2',90,30000),row('2',90,30000)]));expect(r[0].count).toBe(2);expect(r[0].cents).toBe(7000000);expect(r[0].weightedMean).toBeCloseTo((30*10000+90*60000)/70000);expect(v.summary.partial).toBe(1);expect(v.summary.pending).toBe(r[0].cents);});
 it('faturamento futuro entra apenas no histórico anterior e dias seguem a referência',()=>{const d=ds([row('1',180,10000,'A','SP','Cliente A','2026-08-01'),row('2',90,30000)]);const {v,r}=view(d,f({months:[6]}));expect(r[0].count).toBe(1);expect(r[0].weightedMean).toBe(88);expect(r[0].cents).toBe(1000000);expect(v.period.end).toBe('2026-06-30');expect(view(d).r[0].weightedMean).toBe(90);});
 it.each(Object.keys(DIMENSIONS) as Dimension[])('aplica participação e ponderação à dimensão %s',dim=>{const {v,r}=view(ds([row('1',30,10000),row('2',90,30000,'B','RJ','Cliente B')]),f(),dim);expect(r.reduce((a,x)=>a+x.cents,0)).toBe(v.summary.pending);expect(r.reduce((a,x)=>a+x.share,0)).toBeCloseTo(1);for(const x of r)expect(Number.isFinite(x.weightedMean)).toBe(true);});
 it.each([{}, {company:['A']},{company:['A','B']},{customerUF:['SP']},{customerUF:['SP','RJ']},{customer:['Cliente A']},{quarters:[3]},{months:[9]},{company:['A'],customerUF:['SP'],months:[9]}] as Partial<Filters>[])('respeita os filtros integrados %j',filters=>{const {v,r}=view(ds([row('1',30,10000),row('1',90,30000,'B','RJ','Cliente B'),row('3',180,60000,'A','SP','Cliente A')]),f(filters));expect(r.reduce((a,x)=>a+x.cents,0)).toBe(v.summary.pending);expect(r.reduce((a,x)=>a+x.share,0)).toBeCloseTo(1);for(const item of r){const records=v.surgeries.flatMap(s=>s.records.filter(x=>x.customer===item.name&&(!x.billingDate||x.billingDate>v.period.end!)).map(x=>({days:s.days,cents:x.cents})));expect(item.weightedMean).toBe(weightedRetentionDays(records));}});
 it('saldo zero e ausência de dados não produzem divisão por zero',()=>{const {r}=view(ds([row('1',30,0)]));expect(r[0].share).toBe(0);expect(r[0].weightedMean).toBe(0);expect(formatRankingPercent(r[0].share)).toBe('0,00%');expect(weightedRetentionDays([])).toBe(0);expect(executiveRanking([],'customer',null,0)).toEqual([]);});
});
