import {useMemo,useState} from 'react';
import {fmtMoney,fmtNumber,type Dataset} from '../lib/domain';
import {auditRows,normalizeAudit,reviewCount,severityLabel,type AuditSeverity} from '../lib/audit';
import {downloadAudit} from '../lib/audit-export';
export function AuditPanel({dataset}:{dataset:Dataset}){
 const [query,setQuery]=useState(''),[severity,setSeverity]=useState<AuditSeverity>('all'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ds=useMemo(()=>normalizeAudit(dataset),[dataset]);
 const rows=useMemo(()=>auditRows(ds,query,severity),[ds,query,severity]);
 const count=useMemo(()=>reviewCount(ds),[ds]);
 async function download(){setBusy(true);setError('');try{await downloadAudit(rows,ds.asOf);}catch{setError('Não foi possível exportar as ocorrências.');}finally{setBusy(false);}}
 const indicators=[['Registros originais',ds.audit.sourceRows],['Cirurgias distintas (origem)',ds.audit.distinctAppointments],['Agendamentos repetidos',ds.audit.repeatedAppointments],['Empresas',ds.audit.companies],['Total financeiro original',fmtMoney(ds.audit.totalCents)],['Total financeiro válido',fmtMoney(ds.audit.validCents)],['Valor em quarentena',fmtMoney(ds.audit.quarantinedCents)],['Registros inconsistentes',ds.audit.inconsistentRecords],['Datas inválidas',ds.audit.invalidDates],['Faturamentos anteriores',ds.audit.billingBeforeSurgery],['Registros para conferência',count],['Possíveis duplicidades preservadas',ds.audit.exactDuplicateRows]];
 return <section className="panel"><div className="panel-heading"><div><h2>Auditoria da base oficial</h2><p>Base original reconciliada com os registros válidos e a quarentena · inconsistências não corrigidas silenciosamente</p></div><div className="audit-controls"><label className="table-search"><input aria-label="Pesquisar ocorrência" placeholder="Pesquisar ocorrência..." value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={!query} onClick={()=>setQuery('')}>Limpar pesquisa</button><select aria-label="Severidade das ocorrências" value={severity} onChange={e=>setSeverity(e.target.value as AuditSeverity)}><option value="all">Todas as ocorrências</option><option value="warning">Conferir</option><option value="error">Quarentena</option></select><button disabled={busy} onClick={()=>void download()}>Exportar Ocorrências (.xlsx)</button></div></div><div className="audit-grid">{indicators.map(([name,value])=><div key={name}><span>{name}</span><b>{typeof value==='number'?fmtNumber(value):value}</b></div>)}</div>{error&&<p role="alert" className="base-feedback error">{error}</p>}<p className="caption">{ds.issues.length} ocorrências · {count} registros para conferência · {ds.audit.quarantinedRows} registros em quarentena</p><details className="issues"><summary>Conferir {rows.length} ocorrências{query||severity!=='all'?` de ${ds.issues.length}`:''}</summary><div className="table-scroll"><table><thead><tr><th>Linha</th><th>Agendamento</th><th>Severidade</th><th>Ocorrência</th></tr></thead><tbody>{rows.map((i,n)=><tr key={n}><td>{i.row}</td><td>{i.appointment||'—'}</td><td>{severityLabel(i.severity)}</td><td>{i.message}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Nenhuma ocorrência encontrada.</p>}</div></details></section>;
}
