import {useEffect,useRef,useState} from 'react';
import {Database,Download,Upload,RefreshCw,LoaderCircle} from 'lucide-react';
import {parseFile} from '../lib/import';
import {downloadTemplate} from '../lib/downloads';
import {isoToday,fmtMoney,fmtNumber,type Dataset} from '../lib/domain';
export function BaseManagement({dataset,onUpdate}:{dataset:Dataset|null;onUpdate:(dataset:Dataset)=>void}){
 const input=useRef<HTMLInputElement>(null);const generation=useRef(0);
 const [cut,setCut]=useState(dataset?.asOf??isoToday()),[pending,setPending]=useState<Dataset|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(dataset&&!pending)setCut(dataset.asOf);},[dataset]);
 const dates=dataset?.records.map(r=>r.surgeryDate).sort()??[];
 const formatted=(s:string)=>s.split('-').reverse().join('/');
 async function select(file:File){const ticket=++generation.current;setPending(null);setMessage('');setError('');setBusy(true);try{const result=await parseFile(file,cut);if(ticket!==generation.current)return;setPending(result.dataset);setMessage(`Arquivo validado: ${file.name} · ${fmtNumber(result.dataset.audit.sourceRows)} registros, ${fmtNumber(result.dataset.audit.distinctAppointments)} cirurgias. ${result.dataset.audit.quarantinedRows} registros em quarentena (${fmtMoney(result.dataset.audit.quarantinedCents)}). Revise e clique em Atualizar Dashboard.`);}catch(e){if(ticket===generation.current)setError(e instanceof Error?e.message:'Arquivo inválido. A base ativa foi preservada.');}finally{if(ticket===generation.current)setBusy(false);}}
 async function apply(){if(!pending)return;setBusy(true);setError('');setMessage('');try{
  // Yield so the busy state is visible. Publish one validated dataset to every existing component.
  await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
  const next={...pending,updatedAt:new Date().toISOString()};onUpdate(next);setPending(null);if(input.current)input.current.value='';setMessage(`Atualização concluída: ${fmtNumber(next.audit.sourceRows)} registros importados (${fmtNumber(next.audit.validRows)} válidos), ${fmtNumber(next.audit.distinctAppointments)} cirurgias. Os filtros existentes foram preservados.`);
 }catch{setError('Não foi possível atualizar. A base anterior foi preservada.');}finally{setBusy(false);}}
 return <section className="panel base-management" aria-labelledby="base-management-title"><h2 id="base-management-title"><Database size={16}/>Gerenciamento da Base de Dados</h2><div className="base-cards"><button disabled={busy} onClick={async()=>{setError('');try{await downloadTemplate();}catch{setError('Não foi possível baixar o modelo. Tente novamente.');}}}><Download size={19}/><span><b>Baixar Modelo da Base</b><small>Retenção de Faturamento (.xlsx)</small></span></button><button disabled={busy} onClick={()=>input.current?.click()}><Upload size={19}/><span><b>Selecionar Nova Base</b><small>{pending?.fileName??'Arquivo Excel (.xlsx)'}</small></span></button><button className="base-apply" disabled={!pending||busy} onClick={()=>void apply()}>{busy?<LoaderCircle className="spin" size={19}/>:<RefreshCw size={19}/>}<span><b>{busy?'Processando…':'Atualizar Dashboard'}</b><small>{pending?'Aplicar nova base de dados':'Base ativa em uso'}</small></span></button></div><input ref={input} className="base-file-input" aria-label="Selecionar planilha da base" type="file" accept=".xlsx,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)void select(file);e.target.value='';}}/><div className="base-cut"><label>Data de corte da nova base<input type="date" max={isoToday()} value={cut} disabled={busy} onChange={e=>{generation.current++;setCut(e.target.value);setPending(null);setMessage('');setError('');}}/></label><span>Arquivos selecionados são processados apenas neste navegador. A atualização não altera a base compartilhada e é descartada ao recarregar.</span></div>{error&&<p className="base-feedback error" role="alert">{error}</p>}{message&&<p className="base-feedback" role="status">{message}</p>}<div className="base-info"><span><b>Última atualização:</b> {dataset?new Date(dataset.updatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Nenhuma base carregada'}</span><span><b>Arquivo:</b> {dataset?.fileName??'—'}</span><span><b>Empresa(s):</b> {dataset?fmtNumber(dataset.audit.companies):'—'}</span><span><b>Registros:</b> {dataset?fmtNumber(dataset.audit.sourceRows):'—'}</span><span><b>Cirurgias:</b> {dataset?fmtNumber(dataset.audit.distinctAppointments):'—'}</span><span title="Período dos registros financeiros válidos"><b>Período:</b> {dates.length?`${formatted(dates[0])} a ${formatted(dates.at(-1)!)}`:'—'}</span></div></section>;
}
