import {useEffect,useMemo,useState,useRef,type ReactNode,Fragment} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {Activity,Calendar,CheckCircle2,Clock,Download,ShieldCheck,Wallet,ChevronDown,ChevronRight,Search,AlertTriangle,Building2} from 'lucide-react';
import {request,adminRequest,type AdminSession} from './lib/api';
import {AuditPanel} from './components/AuditPanel';
import {downloadReport} from './lib/downloads';
import {BaseManagement} from './components/BaseManagement';
import {buildView,defaultFilters,DIMENSIONS,BANDS,COLORS,STATUSES,fmtMoney,fmtNumber,type Dataset,type Filters,type Dimension} from './lib/domain';
import {MultiSelect} from './components/MultiSelect';
import {executiveRanking,formatRankingPercent,formatWeightedDays} from './lib/executive-ranking';
const monthNames=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const dateLabel=(date:string|null)=>date?date.split('-').reverse().join('/'):'—';
const EMPTY_DATASET:Dataset={id:'',fileName:'',updatedAt:'',asOf:'',records:[],issues:[],audit:{sourceRows:0,validRows:0,quarantinedRows:0,totalCents:0,validCents:0,quarantinedCents:0,distinctAppointments:0,repeatedAppointments:0,companies:0,globalCollisions:0,exactDuplicateRows:0,invalidDates:0,billingBeforeSurgery:0,notesWithoutDate:0,inconsistentRecords:0}};
function Panel({title,sub,children,actions}:{title:string;sub?:string;children:ReactNode;actions?:ReactNode}){return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{actions}</div>{children}</section>;}
function Kpi({title,value,sub,icon,kind='stock'}:{title:string;value:string;sub:string;icon:ReactNode;kind?:string}){return <div className={`kpi ${kind}`}><div><p>{title}</p><strong>{value}</strong><small>{sub}</small></div><span className="kpi-icon">{icon}</span></div>;}
export default function App(){
 const [base,setDs]=useState<Dataset|null>(null),[sessionBase,setSessionBase]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[f,setF]=useState<Filters>(defaultFilters),[rankDim,setRankDim]=useState<Dimension>('customer'),[top,setTop]=useState('10'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[expanded,setExpanded]=useState<string|null>(null),[sort,setSort]=useState<'pending'|'days'|'appointment'>('pending'),[descending,setDescending]=useState(true);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Falha na operação.');}finally{setBusy(false);}};
 const [session,setSession]=useState<AdminSession|null>(null);const publicBase=useRef<Dataset|null>(null),accessGeneration=useRef(0),activeSession=useRef(session);activeSession.current=session;
 const ds=base??EMPTY_DATASET;
 function changeSession(next:AdminSession|null){setError('');if(!next||!activeSession.current){setF(previous=>({...previous,doctor:[],representative:[]}));setQuery('');setExpanded(null);}if(!next){accessGeneration.current++;setDs(publicBase.current);setSessionBase(false);}setSession(next);}

 useEffect(()=>{if(!session)return;const ticket=++accessGeneration.current;adminRequest<Dataset|null>('/dataset',session).then(dataset=>{if(ticket===accessGeneration.current){setDs(dataset);setSessionBase(false);}}).catch(e=>{if(ticket===accessGeneration.current){changeSession(null);setError(e.message);}});return()=>{accessGeneration.current++;};},[session?.email]);
 useEffect(()=>{if(session)return;let active=true;request<Dataset|null>('/public/dataset').then(dataset=>{if(active){publicBase.current=dataset;setDs(dataset);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[session?.email]);
 useEffect(()=>{setPage(0);setExpanded(null);},[f,query,sort,descending,base]);
 const v=useMemo(()=>ds?buildView(ds,f):null,[ds,f]);
 const rows=useMemo(()=>v?.surgeries.filter(s=>`${s.appointment} ${s.company} ${s.customer} ${s.hospital} ${s.doctor}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const cmp=sort==='appointment'?a.appointment.localeCompare(b.appointment):a[sort]-b[sort];return descending?-cmp:cmp;})??[],[v,query,sort,descending]);
 const years=useMemo(()=>[...new Set([f.year,...ds.records.map(r=>+r.surgeryDate.slice(0,4))])].sort(),[ds,f.year]);
 const chart=useMemo(()=>v?.monthly.map(m=>({name:monthNames[m.month-1].slice(0,3)+(m.isPartial?'*':''),...Object.fromEntries(m.bands.map((b,i)=>[`b${i}`,b.cents/100])),count:m.count}))??[],[v]);
 const executiveRows=useMemo(()=>v?executiveRanking(v.surgeries,rankDim,v.period.end,v.summary.pending):[],[v,rankDim]);
 const setDim=(dim:Dimension,values:string[])=>setF(p=>({...p,[dim]:values}));
 return <><header><div className="header-inner"><div className="brand"><span className="brand-symbol"><Activity size={24}/></span><div><h1>Dashboard de Retenção de Faturamento · Biosaúde</h1><p>Dashboard Executivo — FY {f.year}</p></div></div><div className="header-right"><div className="update"><CheckCircle2 size={16}/><div><b>Última atualização da base</b><span>{base?new Date(ds.updatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Base ainda não importada'}{base&&` · ${fmtNumber(ds.audit.sourceRows)} registros`}</span></div></div></div></div></header><main>
 <div className="toolbar"><div><span className="badge"><ShieldCheck size={13}/>{sessionBase?'BASE DA SESSÃO':session?'BASE ADMINISTRATIVA':'BASE ANONIMIZADA'}</span><span className="muted">Posição: <b>{dateLabel(v?.period.end??null)}</b> {v?.period.partial?'· Período parcial':''}</span></div><div className="actions"><button disabled={busy||!base} onClick={()=>run(()=>downloadReport('xlsx',ds,f))}><Download size={15}/>Excel</button><button disabled={busy||!base} onClick={()=>run(()=>downloadReport('pdf',ds,f))}><Download size={15}/>PDF</button></div></div>
 {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')}>Fechar</button></div>}
 {ds&&ds.audit.quarantinedRows>0&&<div className="notice warning"><AlertTriangle size={18}/><span><b>{ds.audit.quarantinedRows} registros em quarentena · {fmtMoney(ds.audit.quarantinedCents)}</b> excluídos dos indicadores por inconsistências. A auditoria ao final da página mantém a rastreabilidade.</span><a href="#auditoria">Ver auditoria</a></div>}
 <>
 <Panel title="Filtros" sub="Dimensões financeiras integradas · saldo no fechamento e faturamento no período" actions={<button className="text-button" onClick={()=>setF({...defaultFilters(),year:ds.asOf?+ds.asOf.slice(0,4):f.year})}>Limpar filtros</button>}>
 <div className="filter-grid"><div className="filter"><label className="filter-label" htmlFor="year">Ano</label><select id="year" value={f.year} onChange={e=>setF(p=>({...p,year:+e.target.value,quarters:[],months:[]}))}>{years.map(y=><option key={y}>{y}</option>)}</select></div>
 <MultiSelect label="Quarter" options={[1,2,3,4].map(q=>({value:String(q),label:`Q${q}`}))} selected={f.quarters.map(String)} onChange={values=>setF(p=>({...p,quarters:values.map(Number)}))}/>
 <MultiSelect label="Mês" options={monthNames.map((name,i)=>({value:String(i+1),label:name}))} selected={f.months.map(String)} onChange={values=>setF(p=>({...p,months:values.map(Number)}))}/>
 {(Object.keys(DIMENSIONS) as Dimension[]).map(dim=><MultiSelect key={['doctor','representative'].includes(dim)?`${dim}-${session?.email??'public'}`:dim} label={DIMENSIONS[dim]} options={[...new Set(ds.records.map(r=>r[dim]))].sort().map(o=>({value:o,label:o}))} selected={f[dim]??[]} onChange={values=>setDim(dim,values)}/>)}
 <MultiSelect label="Situação do Faturamento" options={STATUSES.map(s=>({value:s,label:s}))} selected={f.statuses} onChange={values=>setF(p=>({...p,statuses:values as typeof p.statuses}))}/>
 <MultiSelect label="Faixa de Retenção" options={BANDS.map((b,i)=>({value:String(i),label:b}))} selected={f.bands.map(String)} onChange={values=>setF(p=>({...p,bands:values.map(Number)}))}/></div>
 <div className="filter-foot"><span>Base confirmada até <b>{dateLabel(ds.asOf)}</b> · {fmtNumber(ds.audit.validRows)} registros válidos</span><span>Estoque: último fechamento selecionado · Fluxo: meses selecionados</span></div></Panel>
 {v&&<>{!v.period.end&&<div className="notice warning">Sem fechamento disponível para o período selecionado. Períodos futuros não são exibidos como realizados.</div>}
 <div className="kpi-grid"><Kpi title="Valor total pendente" value={fmtMoney(v.summary.pending)} sub="Estoque no fechamento" icon={<Wallet size={20}/>}/><Kpi title="Cirurgias pendentes" value={fmtNumber(v.summary.count)} sub="Agendamentos distintos, incluindo parciais" icon={<Activity size={20}/>}/><Kpi title="Retenção média" value={`${fmtNumber(v.summary.mean,1)} dias`} sub="Média simples das cirurgias pendentes" icon={<Clock size={20}/>}/><Kpi title="Faturado no período" value={fmtMoney(v.flowCents)} sub="Fluxo · data de faturamento no período" icon={<CheckCircle2 size={20}/>} kind="flow"/><Kpi title="Cirurgias faturadas no período" value={fmtNumber(v.flowCount)} sub="Com ao menos um registro faturado" icon={<Calendar size={20}/>} kind="flow"/><Kpi title="Parcialmente faturadas" value={fmtNumber(v.summary.partial)} sub="Estoque · saldo faturado e pendente" icon={<Building2 size={20}/>}/></div>
 <div className="section-title"><h2>Distribuição da retenção</h2><span>Faixas exclusivas · variação desde {dateLabel(v.period.previous)}</span></div><div className="band-grid">{v.summary.bands.map((b,i)=>{const delta=b.cents-v.previous.bands[i].cents;return <button className={`band-card ${f.bands.includes(i)?'selected':''}`} key={b.label} style={{borderTopColor:COLORS[i]}} onClick={()=>setF(p=>({...p,bands:p.bands.includes(i)?p.bands.filter(b=>b!==i):[...p.bands,i]}))}><div className="band-title"><b>{b.label}</b><span>{fmtNumber(b.share*100,1)}%</span></div><strong>{fmtMoney(b.cents)}</strong><p>{fmtNumber(b.count)} cirurgias · média {fmtNumber(b.mean,1)} dias</p><small className={delta>0?'negative':'positive'}>{delta>=0?'+':''}{fmtMoney(delta)} vs. anterior</small></button>;})}</div>
 <div className="charts-grid"><Panel title="Evolução mensal do saldo retido" sub="Saldos no fechamento · os valores mensais não são somados como faturamento"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:10,right:12,left:8,bottom:4}}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="#edf0f3"/><XAxis dataKey="name" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={n=>`${fmtNumber(n/1000000,1)} mi`} axisLine={false} tickLine={false}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="chart-tooltip"><b>{label}</b><p>{chart.find(c=>c.name===label)?.count} cirurgias pendentes</p>{payload.map((p,i)=><p key={i}>{p.name}: {fmtMoney(Number(p.value)*100)}</p>)}</div>:null}/><Legend wrapperStyle={{fontSize:10}}/>{BANDS.map((b,i)=><Bar key={b} dataKey={`b${i}`} name={b} stackId="retention" fill={COLORS[i]} maxBarSize={55}/>)}</BarChart></ResponsiveContainer></div></Panel>
 <Panel title="Fechamentos trimestrais" sub="Comparação por posição financeira, com distribuição por faixa"><div className="quarter-list">{v.quarterly.map(q=><div className="quarter" key={q.quarter}><div><b>Q{q.quarter}{q.isPartial?' · parcial':''}</b><span>{dateLabel(q.at)}</span><strong>{fmtMoney(q.pending)}</strong></div><div className="quarter-bands">{q.bands.map((b,i)=><span key={i} title={`${b.label}: ${fmtMoney(b.cents)} · ${b.count} cirurgias`} style={{width:`${b.share*100}%`,background:COLORS[i]}}/>)}</div><div className="quarter-metrics"><span>{q.count} cirurgias · {fmtNumber(q.mean,1)} dias</span><span className={q.delta>0?'negative':'positive'}>{q.delta>=0?'+':''}{fmtMoney(q.delta)}</span></div></div>)}{v.quarterly.length===0&&<p className="empty">Nenhum fechamento disponível.</p>}</div></Panel></div>
 <Panel title="Movimentação entre faixas" sub={`Transição de ${dateLabel(v.period.previous)} para ${dateLabel(v.period.end)} · valores retidos comuns e liberações, sem dupla contagem`}><div className="movement-grid">{v.movements.map(m=><div key={m.name}><span>{m.name}</span><strong>{fmtMoney(m.cents)}</strong><small>{m.count} cirurgias</small></div>)}</div><p className="caption">Migrações consideram o mesmo agendamento nos dois fechamentos. Liberações parciais aparecem separadamente do saldo que permaneceu retido. Com filtros de situação/faixa, a movimentação descreve entradas e saídas do recorte.</p></Panel>
 <Panel title="Rankings executivos" sub="Valores pendentes por dimensão · quantidades distintas dentro de cada grupo" actions={<div className="actions"><select aria-label="Dimensão do ranking" value={rankDim} onChange={e=>setRankDim(e.target.value as Dimension)}>{(['company','customer','hospital','representative','customerUF','hospitalUF','type'] as Dimension[]).map(d=><option value={d} key={d}>{DIMENSIONS[d]}</option>)}</select><select aria-label="Limite do ranking" value={top} onChange={e=>setTop(e.target.value)}>{['5','10','15','20','todos'].map(t=><option key={t} value={t}>{t==='todos'?'Todos':`Top ${t}`}</option>)}</select></div>}><div className="ranking" role="region" aria-label="Ranking executivo" tabIndex={0}><div className="rank-head"><span>{DIMENSIONS[rankDim]}</span><span>Saldo retido</span><span>% Retenção</span><span>Cirurgias</span><span>Média Pond. (dias)</span></div>{executiveRows.slice(0,top==='todos'?undefined:+top).map((r,i)=><button className="rank-row" key={r.name} onClick={()=>setDim(rankDim,[r.name])}><div><span className="rank-index">{i+1}</span><div><b>{r.name}</b><div className="rank-track"><span style={{width:`${v.rankings[rankDim][0]?.cents?r.cents/v.rankings[rankDim][0].cents*100:0}%`}}/></div></div></div><strong>{fmtMoney(r.cents)}</strong><span>{formatRankingPercent(r.share)}</span><span>{r.count}</span><span>{formatWeightedDays(r.weightedMean)}</span></button>)}{!v.rankings[rankDim].length&&<p className="empty">Nenhum saldo pendente neste recorte.</p>}</div></Panel>
 <Panel title="Tabela analítica por agendamento" sub={`${fmtNumber(rows.length)} cirurgias · expandir para conferir os registros financeiros originais`} actions={<div className="actions"><label className="table-search"><Search size={15}/><input aria-label="Buscar agendamento" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar agendamento, cliente…"/></label><select aria-label="Ordenar tabela" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="pending">Valor pendente</option><option value="days">Dias de retenção</option><option value="appointment">Agendamento</option></select><button aria-label="Inverter ordenação" onClick={()=>setDescending(!descending)}>{descending?'↓':'↑'}</button></div>}><div className="table-scroll"><table className="analytical"><thead><tr>{['','Empresa','Agendamento','Data cirurgia','Tipo','Cliente','UF cliente','Hospital','UF hospital','Médico','Representante','Valor total','Valor faturado','Valor pendente','Dias','Faixa','Situação'].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.slice(page*25,(page+1)*25).map(s=><Fragment key={s.key}><tr><td><button aria-label={`Expandir ${s.appointment}`} onClick={()=>setExpanded(expanded===s.key?null:s.key)}>{expanded===s.key?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button></td><td>{s.company}</td><td><b>{s.appointment}</b></td><td>{dateLabel(s.surgeryDate)}</td><td>{s.type}</td><td>{s.customer}</td><td>{s.customerUF}</td><td>{s.hospital}</td><td>{s.hospitalUF}</td><td>{s.doctor}</td><td>{s.representative}</td><td>{fmtMoney(s.total)}</td><td>{fmtMoney(s.billed)}</td><td><b>{fmtMoney(s.pending)}</b></td><td>{s.band!==null?s.days:'—'}</td><td>{s.band!==null?BANDS[s.band]:'—'}</td><td><span className={`status status-${STATUSES.indexOf(s.status)}`}>{s.status}</span></td></tr>{expanded===s.key&&<tr><td colSpan={17}><div className="record-detail"><b>Registros financeiros · {s.records.length} linhas preservadas</b><table><thead><tr><th>Linha original</th><th>Cliente</th><th>Representante</th><th>Data faturamento</th><th>Nota de cobrança</th><th>Valor</th><th>Situação no fechamento</th></tr></thead><tbody>{s.records.map(r=><tr key={r.id}><td>{r.sourceRow}</td><td>{r.customer}</td><td>{r.representative}</td><td>{dateLabel(r.billingDate)}</td><td>{r.note||'—'}</td><td>{fmtMoney(r.cents)}</td><td>{r.billingDate&&r.billingDate<=v.period.end!?'Faturado':'Pendente'}</td></tr>)}</tbody></table></div></td></tr>}</Fragment>)}</tbody></table>{!rows.length&&<p className="empty">Nenhum agendamento encontrado.</p>}</div><div className="pagination"><span>Página {Math.min(page+1,Math.max(1,Math.ceil(rows.length/25)))} de {Math.max(1,Math.ceil(rows.length/25))} · 25 por página</span><div><button disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><button disabled={(page+1)*25>=rows.length} onClick={()=>setPage(page+1)}>Próxima</button></div></div></Panel>
 <div id="auditoria"><AuditPanel key={session?.email??'public'} dataset={ds}/></div>
 </>}</>
 <BaseManagement session={session} onSession={changeSession} dataset={base} onUpdate={(next,temporary)=>{if(!activeSession.current)return;setDs(next);setSessionBase(temporary);setError('');}}/>
 <footer>BIOSAÚDE · Dashboard Executivo de Retenção de Faturamento · Dados restritos · Pacientes omitidos</footer></main>
 </>;
}
